### ISSUE TITLE
Building to an external directory

### ISSUE THREAD

**Issue by stueynet** [ProjectCleverWeb/Semantic-UI-WordPress#22]
Sorry this is definitely not an issue per se but I am trying to figure out a good workflow for the theme. Where do you currently have the files reside in relation to your WordPress install. I am trying to have it build to the themes directory but it sort of needs me to have those within the working directory. Otherwise its an error that I cannot modify files or folders outside the working directory.

**Comment by ProjectCleverWeb** [comment]
My development environment is basically the same as it is setup for Travis (see [`.travis.yml`](https://github.com/ProjectCleverWeb/Semantic-UI-WordPress/blob/develop/.travis.yml)). I use composer to install WordPress, then setup the `wp-config.php` file, and then set it up as a very basic site (see [`testing/database.sql`](https://github.com/ProjectCleverWeb/Semantic-UI-WordPress/blob/develop/testing/database.sql)); finally I symlink the build directory into the WordPress theme folder. Since I am using a pre-configured database my theme is used instead of the default theme.

As long as this is setup correctly, I just use the `gulp build` and `gulp watch` commands to manage the build directory while I modify the source directory. Although your issue with modifying files sounds like a permissions problem.

Since WordPress is installed to `testing/vendor/wordpress` within my project (which is also in my `.gitignore` file) I don't run into working directory problems.

I also use [WP Test](http://wptest.io/) whenever I am modifying the theme design.

I should also note that since Travis is only for testing the PHP portion of my code, I don't bother running the build commands and I symlink to the source directory instead of the build directory in my Travis testing environment.

**Comment by stueynet** [comment]
Ah this is helpful. Thanks!

**Comment by ProjectCleverWeb** [comment]
no problem and good luck!
