### ISSUE TITLE
Request: screenshots & demo site

### ISSUE THREAD

**Issue by brandondrew** [ProjectCleverWeb/Semantic-UI-WordPress#25]
Screenshots would probably be sufficient (and quick to add!) but a demo (even just using static pages, rather than an actual WP installation) would be nice.  You'll get more adoption if people can look at something that takes a second to get to, rather than something that requires them to do set up for first.

**Comment by ProjectCleverWeb** [comment]
This is a good idea, I will get that ball rolling

**Comment by destan** [comment]
don't get me wrong but it's more than a "good idea", it's kinda must-have ;)

**Comment by ProjectCleverWeb** [comment]
As I said I will get the ball rolling on this. I understand that it is a need for some people and that is why I have this marked as a planned feature.

However, the project is under active development right now, and creating such a site/screenshots would be a wasted effort because most of the features have been changed since the last release.

That is why I haven't published either a demo or screenshots.


But if you would like to create either of those, I would gladly publish it in the projects readme.

**Comment by ProjectCleverWeb** [comment]
Added screenshots in prep for upcoming 1.0.0 release.

Demo site is coming soon
