### ISSUE TITLE
Fatal error: Allowed memory size of 268435456 bytes exhausted

### ISSUE THREAD

**Issue by fwahlqvist** [ProjectCleverWeb/Semantic-UI-WordPress#33]
Using default theme with no updates and switching off "Show first-run" causes a memory issue with the query vars on template_part_load.php when trying to load the site. 

<code> 
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /Users/***/www/mamp/wp.dev/wordpress/wp-content/themes/dist/include/function/template_part__load.php on line 36
</code>

**Comment by ProjectCleverWeb** [comment]
This is likely caused by one or more of your active plugins. As explained in issue #29, this theme only uses about 11.5MB including WordPress.

If you login as an admin in WordPress and look at the JS console in your browser, you will see that this theme will give you debug output. The last line of which should read something like this: `[PHP] Memory Peak: 11.688 MiB` (taken from my local running instance with no active plugins)

My suggestion is to disable all active plugins; and then, one-by-one re-enable each plugin to see which ones are using a lot of memory using this debug information.

Please let me know if you have any questions, or if this did not resolve your issue

**Comment by fwahlqvist** [comment]
This is on a clean wp multisite install on a local amp.pro not other templates or plugins are activated

**Comment by ProjectCleverWeb** [comment]
Hmm... it is possible one of the plugins is using a lot of memory with just its configuration file.

Can you please confirm that you are using the latest commit from develop? Also, I will try and replicate your environment on my PC but it would be more ideal if you could make a temp install of WordPress with no plugins (as in deleted, not just deactivated) and then re-add them.

I am unfamiliar with "amp.pro" could you point me out to a place I can download it?

**Comment by fwahlqvist** [comment]
Will delete and reinstall wp on local machine, will also delete the default plugins, it should be mamp.pro (https://www.mamp.info/en/mamp-pro/)

**Comment by ProjectCleverWeb** [comment]
I have setup a WordPress 4.3.1 instance on my localhost with PHP 5.6 and have switched WordPress into Multisite mode. But I am still not getting any memory problems? (this on xampp / mamp.pro is still downloading)

```
[PHP] Memory Peak: 12.039 MiB
```

**Comment by ProjectCleverWeb** [comment]
Were you able to recreate this issue with a blank install and no plugins in the plugins directory?

**Comment by fwahlqvist** [comment]
<code>
macbook:Semantic-UI-WordPress xxxxxx$ git branch
* develop
macbook:Semantic-UI-WordPress xxxxxx$ git pull
Already up-to-date.
</code>

Probably a user error as I uploaded the same files to my web hotel and get the same error, to confirm the only thing i have down is to pull down the latest code in dev branch and then used gulp to build the theme and copied "dist" to wp theme folder.

**Comment by ProjectCleverWeb** [comment]
hmm, that is extremely odd. Especially since I cannot recreate it.

Even with an out of memory error the theme debugger \*should\* produce output to the browser's console. Can you please copy/paste that output here? (you must be logged in as an admin in WP in order to see it)

Beyond that can you tell me what version of Apache, MySQL, PHP, and WordPress you are using?

As far as ruling out causes, try adding a `return TRUE;` to the top of the `template_part()` function in  `dist/include/function/template_part.php`. If it is the theme, that function is more than likely the cause.

**Comment by ProjectCleverWeb** [comment]
After some head scratching, I figured out why I couldn't reproduce your error. I wasn't properly synced with Github.

A fix is on the way!

**Comment by fwahlqvist** [comment]
Tested works and thanks! :+1:

**Comment by ProjectCleverWeb** [comment]
No problem, and thanks for reporting this in the first place.
