### ISSUE TITLE
Request: THA implemented in to the default template 

### ISSUE THREAD

**Issue by fwahlqvist** [ProjectCleverWeb/Semantic-UI-WordPress#34]
Although THA (Theme hook alliance) don't have a massive following it would be good to have it included in this build, THA have hooks that don't exist by default yet in WP, for example after body, more info can be found on the GitHub page
https://github.com/zamoose/themehookalliance

**Comment by ProjectCleverWeb** [comment]
This is a great idea, and thanks for mentioning it, but it is outside of the scope of this project. (for now)

## This Project:
The primary goal of this theme is to provide an easy but efficient starting point for developing a WordPress theme on Semantic UI.

It is true that this theme contains many extra parts, such as a built in debugger, OOP, custom menu walker, etc. However, all of these things are either automatically configured or extend existing features of WordPress. (or they will by 1.0.0) The idea is that you will only need to learn a very limited amount to take full advantage of this theme, and it will be a very "vanilla" experience.

## Extended Version:
There is a plan in the works to start development on an "extended" version of this theme, that is intentionally complex. Here are some of the planned features thus far:

- More In-Depth Theme Options
- Basic Template Builder
- Basic Theme Customizer
- Multiple Theme Support
- Basic Form Builder
- Landing Page Builder

And now THA support will be added to that list. However, this project must be polished into something worthy of "1.0.0" first, because the extended version will be based off of this project.

**Comment by ProjectCleverWeb** [comment]
You can see more information about the extended version [here](https://github.com/ProjectCleverWeb/Semantic-UI-WordPress/wiki/Extended-Version-Plans).
