### ISSUE TITLE
Menu Walker multiple menu classes

### ISSUE THREAD

**Issue by fwahlqvist** [ProjectCleverWeb/Semantic-UI-WordPress#35]
Not sure if menu_walker has a bug, currently you can't evenly divide the menu as 
```html
// now display
		echo "<div class=\"ui menu\"><nav class=\"$the_class\" id=\"$the_id\" role=\"navigation\">$items</nav></div>".PHP_EOL;
```
in menu_walker.php have a parent div class with "ui menu" and then a nav class with "menu".
To my understanding the Semantic documentation mentions it should be 

```html
// now display
		echo "<nav class=ui \"$the_class\" id=\"$the_id\" role=\"navigation\">$items</nav></div>".PHP_EOL;
```
Under  "Evenly Divided" at 
http://semantic-ui.com/collections/menu.html

**Comment by ProjectCleverWeb** [comment]
That class is outdated and will be receiving an update. It was originally designed for the `pre-release` of Semantic UI, then modified to work with `1.x.x`, and now it is just barely working with `2.x.x`.

Beyond that, it doesn't follow how WordPress says to do menu walkers.

The whole thing will be re-written from scratch, so I would say don't get to use to using it in its current state.

**Comment by fwahlqvist** [comment]
Thanks you for info.
Do you have a roadmap on what you are working on so i know where I should start? 
Also how do i best contribute?

**Comment by ProjectCleverWeb** [comment]
Right now I am focusing I bringing the project to a point where everything is inline with WordPress documentation and Semantic UI documentation. So things that contradict that, like that menu walker, will be getting updated.

After that, there are still a few templates that need to be configured, mostly just the comments template though. The rest will likely come shortly after 1.0.x as features in 1.1.x. You can see what comments will look like by using `content/comments-draft`, but the code behind generating it isn't configured yet.

Finally, after all that I will be triple checking everything for about a week. Doing everything I can to ensure there are no bugs so 1.0.0 can be released.

Adding any features or enhancements is a secondary priority right now, and most of them will be postponed until after 1.0.0; this is so 1.0.0 can be released sooner rather than later. However, features/enhancements that can be done fairly quickly are an exception to this rule.

---

As far as contributing, finding issues and making suggestions like you have is a **great** help all on its own. :+1: Beyond that, you can also contribute code by forking the repo, making changes, and then submitting a pull request.

Although, prior to making any code changes that involve adding a feature, I would suggest a shooting me a quick email asking if the feature should be in the project. I would hate for you, or any else for that matter, to put effort into something that may end up getting rejected for being out of scope.

**Comment by ProjectCleverWeb** [comment]
I should also mention that part of the semantics of this project is that the code itself should be easy to read and documented (both with code comments and written documentation). So things that contradict that will also be updated.

**For example:** not to long ago I re-wrote the entire gulp configuration without changing how it works, because it was all in one file and had no real structure.

**Comment by fwahlqvist** [comment]
:+1: , thanks for quick reply, fully understand that you will not commit to any timelines but do you have any expectations on when 1.0 will be released ?

**Comment by ProjectCleverWeb** [comment]
I am hoping for inside the next month or month and 1/2, but that is largely dependent on my free time.

There isn't a lot of "hard" work to do but there is plenty of things that need to be addressed, some less obvious than others.

For example, the portion called "dev-notes" will be scrapped in favor Markdown documentation (much simpler solution), and a module will need to be added to gulp to package it within the theme. No part of that is hard, it really just a matter of writing the docs, and then just copying the `gulp build-readme` command and modifying it to work with the docs.

**Comment by ProjectCleverWeb** [comment]
I fixed the original bug for this issue, however at the moment that solution has a display bug that prevents it from showing more than a depth of 2. This new bug will be addressed at a later time, but at least the menu now follows the WordPress documentation.

**Comment by fwahlqvist** [comment]
:+1:

**Comment by ProjectCleverWeb** [comment]
@fwahlqvist Thought I would let you know that 1.0.0 will be released inside the next week.

I am at the point of triple checking everything now, but it **should** be production ready.

**Comment by fwahlqvist** [comment]
:+1:
